=== emreji/ticket-tracker/schemas/supportsystem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="supportsystem">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="supportticket" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ticketnumber" type="xs:string"></xs:element>
                            <xs:element name="issuedate" type="xs:date"></xs:element>
                            <xs:element name="status" type="statustype"></xs:element>
                            <xs:element name="clientid" type="xs:integer"></xs:element>
                            <xs:element name="supportmessage" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="message" type="xs:string"></xs:element>
                                        <xs:element name="time" type="xs:dateTime"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="userid" type="xs:integer" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="category" type="categorytype" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="categorytype">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hardware" />
            <xs:enumeration value="Software" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="statustype">
        <xs:restriction base="xs:string">
            <xs:enumeration value="New" />
            <xs:enumeration value="On-going" />
            <xs:enumeration value="Resolved" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== emreji/ticket-tracker/xml/supportsystem.xml
<?xml version="1.0" encoding="UTF-8"?>
<supportsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/supportsystem.xsd">
    <supportticket category="Software">
        <ticketnumber>A100</ticketnumber>
        <issuedate>2018-01-28</issuedate>
        <status>On-going</status>
        <clientid>986</clientid>
        <supportmessages>
            <supportmessage userid="986">
                <message>Installation failed</message>
                <time>2017-12-28T11:00:00</time>
            </supportmessage>
        </supportmessages>
    </supportticket>
    <supportticket category="Hardware">
        <ticketnumber>A101</ticketnumber>
        <issuedate>2018-02-16</issuedate>
        <status>On-going</status>
        <clientid>465</clientid>
        <supportmessages>
            <supportmessage userid="465">
                <message>Wi-fi not working.</message>
                <time>2018-01-30T09:00:00</time>
            </supportmessage>
        </supportmessages>
    </supportticket>
    <supportticket category="Software">
        <ticketnumber>A104</ticketnumber>
        <issuedate>2018-01-16</issuedate>
        <status>Resolved</status>
        <clientid>465</clientid>
        <supportmessages>
            <supportmessage userid="465">
                <message>Needs more RAM space</message>
                <time>2018-02-16T09:00:00</time>
            </supportmessage>
            <supportmessage userid="289">
                <message>RAM space added</message>
                <time>2018-02-17T09:00:00</time>
            </supportmessage>
        </supportmessages>
    </supportticket>
    <supportticket category="Software">
        <ticketnumber>A108</ticketnumber>
        <issuedate>2018-02-25</issuedate>
        <status>Resolved</status>
        <clientid>234</clientid>
        <supportmessages>
            <supportmessage userid="234">
                <message>Needs permission for further work.</message>
                <time>2018-02-20T12:30:00</time>
            </supportmessage>
            <supportmessage userid="289">
                <message>Permission granted</message>
                <time>2018-02-20T12:30:00</time>
            </supportmessage>
        </supportmessages>
    </supportticket>
<supportticket category="Hardware"><ticketnumber>A105</ticketnumber><issuedate>2018-03-14</issuedate><status>New</status><clientid>234</clientid><supportmessages><supportmessage userid="234"><message>Computer shut down.</message><time>2018-03-30 01:22:07</time></supportmessage></supportmessages></supportticket><supportticket category="Software"><ticketnumber>A300</ticketnumber><issuedate>2018-03-29</issuedate><status>New</status><clientid>234</clientid><supportmessages><supportmessage userid="234"><message>New software required</message><time>2018-03-30 01:22:36</time></supportmessage></supportmessages></supportticket></supportsystem>
