=== emreji/ticket-tracker/Schemas/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstname" type="xs:string"></xs:element>
                                        <xs:element name="lastname" type="xs:string"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="username" type="xs:string"></xs:element>
                            <xs:element name="password" type="xs:string"></xs:element>
                            <xs:element name="position" type="xs:string"></xs:element>
                            <xs:element name="emailid" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                        <xs:attribute name="type" type="usertype" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="usertype">
        <xs:restriction base="xs:string">
            <xs:enumeration value="client" />
            <xs:enumeration value="supportstaff" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== emreji/ticket-tracker/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/users.xsd">
    <user id="234" type="client">
        <name>
            <firstname>Rob</firstname>
            <lastname>Harold</lastname>
        </name>
        <username>rob_harold</username>
        <password>password234</password>
        <position>Assistant Manager</position>
        <emailid>rob.harold@gmail.com</emailid>
    </user>
    <user id="289" type="supportstaff">
        <name>
            <firstname>John</firstname>
            <lastname>Doe</lastname>
        </name>
        <username>john_doe</username>
        <password>password289</password>
        <position>customer support</position>
        <emailid>john.doe@gmail.com</emailid>
    </user>
    <user id="986" type="supportstaff">
        <name>
            <firstname>Doug</firstname>
            <lastname>Smith</lastname>
        </name>
        <username>doug_smith</username>
        <password>password986</password>
        <position>Team Lead</position>
        <emailid>doug.smith@gmail.com</emailid>
    </user>
    <user id="465" type="client">
        <name>
            <firstname>Evelyn</firstname>
            <lastname>Mathew</lastname>
        </name>
        <username>evelyn_mathew</username>
        <password>password465</password>
        <position>Manager</position>
        <emailid>eve.mat@gmail.com</emailid>
    </user>
</users>
